### ISSUE TITLE
CT removing windowWidth / windowHeight by default?

### ISSUE THREAD

**Issue by DanielHeath** [radiopaedia/dicomanon#10]
Loading a CT file (sopclass 1.2.840.10008.5.1.4.1.1.2) strips the window/level - should dxImageModulePolicy be applied to those files by default? Is there ever a situation where window/level is something we want to remove?

**Comment by plwp** [comment]
Added to policy and merged into main.

**Comment by DanielHeath** [comment]
Nice.
